[package]
name = "chapter5"
version = "0.1.0"
authors = ["Andrei Herdt <andrei.herdt@tra.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
